{
 "title": "VictoriaTraces - Drilldown",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "datasource",
    "label": "datasource",
    "query": "victoriametrics-traces-datasource"
   },
   { "name": "service", "label": "service name", "query": { "query": "" } },
   {
    "name": "name",
    "label": "span name",
    "query": {
     "query": "{\"resource_attr:service.name\" in ($service)}"
    }
   },
   {
    "name": "attribute",
    "query": {
     "query": "{\"resource_attr:service.name\" in ($service)} AND {\"name\" in ($name)}"
    }
   },
   { "name": "duration", "label": "Comparison Filter", "query": "duration :> 50us" }
  ]
 },
 "panels": [
  { "title": "Span R.E.D Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Span Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{\"resource_attr:service.name\" in ($service)} AND {\"name\" in ($name)} \n | stats rate()",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "{\"resource_attr:service.name\" in ($service)} AND {\"name\" in ($name)} AND status_code:=\"2\" | stats rate()",
     "legendFormat": "err rate"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "{\"resource_attr:service.name\" in ($service)} AND {\"name\" in ($name)} | stats histogram(duration)"
    }
   ]
  },
  { "title": "Span Attributes ($attribute)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Count",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{\"resource_attr:service.name\" in ($service)} AND {\"name\" in ($name)} AND \"$attribute\":!\"\" | stats by (\"$attribute\") count() total\n| sort by(total) desc ",
     "legendFormat": "{{$attribute}}"
    }
   ]
  },
  {
   "title": "Count - With LogsQL Filter",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{\"resource_attr:service.name\" in ($service)} AND {\"name\" in ($name)} AND \"$attribute\":!\"\" AND ($duration)  | stats by (\"$attribute\") count() total\n| sort by(total) desc ",
     "legendFormat": "{{$attribute}}"
    }
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{\"resource_attr:service.name\" in ($service)} AND {\"name\" in ($name)} AND \"$attribute\":!\"\" | stats by (\"$attribute\") rate() rate\n| sort by(rate) desc",
     "legendFormat": "{{$attribute}}"
    }
   ]
  },
  {
   "title": "Rate - With LogsQL Filter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{\"resource_attr:service.name\" in ($service)} AND {\"name\" in ($name)} AND \"$attribute\":!\"\" AND ($duration) | stats by (\"$attribute\") rate() rate\n| sort by(rate) desc ",
     "legendFormat": "{{$attribute}}"
    }
   ]
  },
  {
   "title": "Duration - P90",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "{\"resource_attr:service.name\" in ($service)} AND {\"name\" in ($name)} AND (\"$attribute\" :! \"\") | stats by (\"$attribute\") quantile(0.9, duration) p90",
     "legendFormat": "{{$attribute}}"
    }
   ]
  },
  {
   "title": "Duration - P90 - With LogsQL Filter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "{\"resource_attr:service.name\" in ($service)} AND {\"name\" in ($name)} AND (\"$attribute\" :! \"\")  AND ($duration) | stats by (\"$attribute\") quantile(0.9, duration) p90",
     "legendFormat": "{{$attribute}}"
    }
   ]
  },
  { "title": "View Traces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Trace Spans",
   "type": "logs",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "{\"resource_attr:service.name\" in ($service)} AND {\"name\" in ($name)} AND {\"resource_attr:service.name\" != \"\"} AND ($duration) | pack_logfmt fields (trace_id, span_id) as _msg | sort by (_time)"
    }
   ]
  },
  { "title": "Trace Explorer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Trace charts",
   "type": "victoriametrics-traces-charts-panel",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
   "targets": [
    { "entity": "traces", "limit": 50 }
   ]
  },
  {
   "title": "Traces",
   "type": "victoriametrics-traces-panel",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 52 },
   "targets": [
    { "entity": "traces", "limit": 50 }
   ]
  }
 ]
}